name: flutter_exam
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  logger: ^2.3.0
  line_icons: ^2.0.3
  dio: ^5.4.3+1
  animated_splash_screen: ^1.3.0
  http: ^1.2.1
  mockito: ^5.4.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  test: ^1.20.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
